"""Generate C register headers from the register maps extracted from datasheets.

Transcribing a register map out of a PDF by hand is tedious and is exactly where
transposed digits creep in. The addresses are already indexed, so the header can
be generated — each `#define` carrying the datasheet page it came from, so a
reviewer can check it in seconds.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence

from .store import Store


@dataclass
class RegisterDef:
    name: str
    address: str
    page: Optional[int]
    description: str = ""


def _ident(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", str(text)).strip("_").upper() or "DEV"


def collect_registers(store: Store, part: str) -> List[RegisterDef]:
    """All registers indexed for a part, de-duplicated by name, lowest page first."""
    rows = store.find_registers("", part=part, limit=1000)
    best: Dict[str, RegisterDef] = {}
    for row in rows:
        name = (row["name"] or "").strip()
        if not name:
            continue
        candidate = RegisterDef(
            name=name,
            address=(row["address"] or "").lower(),
            page=row["page"],
            description=(row["description"] or "").strip(),
        )
        existing = best.get(name)
        if existing is None or (candidate.page or 0) < (existing.page or 0):
            best[name] = candidate
        elif not existing.description and candidate.description:
            existing.description = candidate.description
    return sorted(best.values(), key=lambda r: (_addr_int(r.address), r.name))


def _addr_int(addr: str) -> int:
    try:
        return int(addr, 16) if addr.lower().startswith("0x") else int(addr)
    except (ValueError, AttributeError):
        return 1 << 30  # sort unparsable addresses last


def generate_header(
    part: str,
    registers: Sequence[RegisterDef],
    *,
    source: str = "",
    address_width: int = 2,
) -> str:
    """Render a self-contained register header for one part."""
    tag = _ident(part)
    guard = f"{tag}_REGS_H"
    stamp = time.strftime("%Y-%m-%d")

    lines = [
        f"/* {part} register map — generated by fwcopilot on {stamp}.",
        f" * Source: {source or 'indexed datasheet'}",
        " *",
        " * Extracted automatically from the datasheet's register tables. Page numbers",
        " * are given so each address can be verified against the source in seconds.",
        " * Regenerate with: fwcopilot regs " + part,
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
    ]

    if not registers:
        lines += [
            f"/* No register entries were extracted for {part}.",
            " * The datasheet may present its register map as a graphic or an",
            " * irregular table; transcribe the addresses by hand here.",
            " */",
            "",
            f"#endif /* {guard} */",
        ]
        return "\n".join(lines) + "\n"

    macros = [f"#define {tag}_REG_{reg.name}" for reg in registers]
    macro_width = max(len(m) for m in macros)
    addrs = [_format_addr(reg.address, address_width) + "u" for reg in registers]
    addr_width = max(len(a) for a in addrs)

    for reg, macro, addr in zip(registers, macros, addrs):
        comment_bits = []
        if reg.description:
            comment_bits.append(reg.description)
        if reg.page:
            comment_bits.append(f"p.{reg.page}")
        comment = f"  /* {' — '.join(comment_bits)} */" if comment_bits else ""
        lines.append(f"{macro:<{macro_width}}  {addr:<{addr_width}}{comment}")

    lines += [
        "",
        f"/* Convenience: number of registers extracted for {part}. */",
        f"#define {tag}_REG_COUNT {len(registers)}u",
        "",
        f"#endif /* {guard} */",
    ]
    return "\n".join(lines) + "\n"


def _format_addr(addr: str, width: int) -> str:
    try:
        value = int(addr, 16) if addr.lower().startswith("0x") else int(addr)
    except (ValueError, AttributeError):
        return addr or "0x00"
    digits = max(width, 2 if value <= 0xFF else 4)
    return f"0x{value:0{digits}X}"


def available_parts(store: Store) -> List[str]:
    seen: List[str] = []
    for row in store.list_docs("datasheet"):
        label = row["part"] or row["title"]
        if label and label not in seen:
            seen.append(label)
    return seen
