"""Deterministic firmware code generation from the board profile.

Nothing here calls the model: given `board.yaml`, the pin map, buses and device
addresses are already exact, so the pin header, driver skeletons, linker script
and build files are generated directly. The assistant then works *on top of*
generated code that already matches the hardware.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .board import BoardProfile, Component

TARGETS = ("cmsis-bare", "platformio", "zephyr", "drivers-only")


@dataclass
class GeneratedFile:
    path: str
    content: str
    existed: bool = False


def _ident(text: str) -> str:
    out = re.sub(r"[^A-Za-z0-9]+", "_", str(text)).strip("_")
    return out or "dev"


def _upper(text: str) -> str:
    return _ident(text).upper()


def _lower(text: str) -> str:
    return _ident(text).lower()


def _addr_literal(value: Any) -> str:
    if isinstance(value, int):
        return f"0x{value:02X}"
    text = str(value).strip()
    if text.lower().startswith("0x"):
        return "0x" + text[2:].upper()
    try:
        return f"0x{int(text):02X}"
    except ValueError:
        return text


def _header_guard(name: str) -> str:
    return _upper(name) + "_H"


# --------------------------------------------------------------------------
# board_pins.h — the highest-value generated artifact
# --------------------------------------------------------------------------

def gen_board_pins(board: BoardProfile) -> str:
    name = _upper(board.name)
    lines = [
        "/* Generated by fwcopilot from board.yaml — do not edit by hand.",
        f" * Board: {board.name}"
        + (f" rev {board.board.get('revision')}" if board.board.get("revision") else ""),
        " * Regenerate with: fwcopilot scaffold --target drivers-only",
        " */",
        f"#ifndef {name}_PINS_H",
        f"#define {name}_PINS_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    mcu = board.mcu
    if mcu:
        lines.append("/* MCU */")
        if mcu.get("part"):
            lines.append(f'#define BOARD_MCU_PART        "{mcu["part"]}"')
        if mcu.get("clock_hz"):
            lines.append(f"#define BOARD_SYSCLK_HZ       {int(mcu['clock_hz'])}u")
        if mcu.get("flash_kb"):
            lines.append(f"#define BOARD_FLASH_BYTES     ({int(mcu['flash_kb'])}u * 1024u)")
        if mcu.get("ram_kb"):
            lines.append(f"#define BOARD_RAM_BYTES       ({int(mcu['ram_kb'])}u * 1024u)")
        lines.append("")

    if board.pins:
        lines.append("/* Pin map (net name -> MCU pin) */")
        width = max((len(_upper(p.get("net") or p.get("function") or p.get("pin"))) for p in board.pins), default=8)
        for pin in board.pins:
            net = _upper(pin.get("net") or pin.get("function") or pin.get("pin"))
            pad = " " * max(1, width + 4 - len(net))
            comment_bits = []
            if pin.get("function"):
                comment_bits.append(str(pin["function"]))
            if pin.get("af") is not None:
                comment_bits.append(f"AF{pin['af']}")
            if pin.get("to"):
                comment_bits.append(f"-> {pin['to']}")
            if pin.get("active"):
                comment_bits.append(f"active-{pin['active']}")
            comment = f"  /* {', '.join(comment_bits)} */" if comment_bits else ""
            lines.append(f'#define PIN_{net}{pad}"{pin.get("pin")}"{comment}')
        lines.append("")

    if board.buses:
        lines.append("/* Buses */")
        for bus in board.buses:
            bus_id = _upper(bus.get("name"))
            if bus.get("speed_hz"):
                lines.append(f"#define BUS_{bus_id}_HZ          {int(bus['speed_hz'])}u")
            if bus.get("baud"):
                lines.append(f"#define BUS_{bus_id}_BAUD        {int(bus['baud'])}u")
            for role, pin in (bus.get("pins") or {}).items():
                lines.append(f'#define BUS_{bus_id}_{_upper(role)}{" " * 8}"{pin}"')
        lines.append("")

    comps = board.components
    if comps:
        lines.append("/* On-board devices */")
        for comp in comps:
            tag = _upper(comp.part or comp.ref)
            if comp.address is not None:
                lines.append(f"#define {tag}_I2C_ADDR         {_addr_literal(comp.address)}u")
            if comp.bus_name:
                lines.append(f'#define {tag}_BUS              "{comp.bus_name}"')
            if comp.bus.get("cs"):
                lines.append(f'#define {tag}_CS_PIN           "{comp.bus["cs"]}"')
        lines.append("")

    lines.append(f"#endif /* {name}_PINS_H */")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Per-component driver skeletons
# --------------------------------------------------------------------------

I2C_HEADER = """\
/* Generated by fwcopilot from board.yaml.
 * Device: {part} ({ref}){role_comment}
 * Bus: {bus} @ {addr}
 *
 * Transport-agnostic: supply read/write callbacks backed by your HAL so this
 * driver stays portable and unit-testable.
 */
#ifndef {guard}
#define {guard}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define {tag}_I2C_ADDRESS {addr}u

/* Return 0 on success, negative on error. */
typedef int (*{lname}_i2c_read_fn)(uint8_t addr, uint8_t reg, uint8_t *buf, size_t len, void *ctx);
typedef int (*{lname}_i2c_write_fn)(uint8_t addr, uint8_t reg, const uint8_t *buf, size_t len, void *ctx);
typedef void (*{lname}_delay_ms_fn)(uint32_t ms);

typedef struct {{
    {lname}_i2c_read_fn  read;
    {lname}_i2c_write_fn write;
    {lname}_delay_ms_fn  delay_ms;
    void                *ctx;
    uint8_t              address;   /* defaults to {tag}_I2C_ADDRESS */
}} {lname}_t;

int {lname}_init({lname}_t *dev);
int {lname}_read_reg({lname}_t *dev, uint8_t reg, uint8_t *value);
int {lname}_write_reg({lname}_t *dev, uint8_t reg, uint8_t value);
int {lname}_read_burst({lname}_t *dev, uint8_t reg, uint8_t *buf, size_t len);

#endif /* {guard} */
"""

I2C_SOURCE = """\
/* Generated by fwcopilot from board.yaml. Fill in the TODOs from the datasheet:
 * {datasheet_hint}
 */
#include "{header}"

int {lname}_read_reg({lname}_t *dev, uint8_t reg, uint8_t *value)
{{
    if (dev == NULL || dev->read == NULL || value == NULL) {{
        return -1;
    }}
    return dev->read(dev->address, reg, value, 1u, dev->ctx);
}}

int {lname}_write_reg({lname}_t *dev, uint8_t reg, uint8_t value)
{{
    if (dev == NULL || dev->write == NULL) {{
        return -1;
    }}
    return dev->write(dev->address, reg, &value, 1u, dev->ctx);
}}

int {lname}_read_burst({lname}_t *dev, uint8_t reg, uint8_t *buf, size_t len)
{{
    if (dev == NULL || dev->read == NULL || buf == NULL) {{
        return -1;
    }}
    return dev->read(dev->address, reg, buf, len, dev->ctx);
}}

int {lname}_init({lname}_t *dev)
{{
    if (dev == NULL || dev->read == NULL || dev->write == NULL) {{
        return -1;
    }}
    if (dev->address == 0u) {{
        dev->address = {tag}_I2C_ADDRESS;
    }}

    /* TODO: read the WHO_AM_I / chip-ID register and verify it against the
     * datasheet value, then apply the documented reset and power-up sequence
     * (including any mandatory delay) before configuring the device. */
    return 0;
}}
"""

SPI_HEADER = """\
/* Generated by fwcopilot from board.yaml.
 * Device: {part} ({ref}){role_comment}
 * Bus: {bus}{cs_comment}
 */
#ifndef {guard}
#define {guard}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Return 0 on success, negative on error. */
typedef int (*{lname}_spi_xfer_fn)(const uint8_t *tx, uint8_t *rx, size_t len, void *ctx);
typedef void (*{lname}_cs_fn)(bool asserted, void *ctx);
typedef void (*{lname}_delay_ms_fn)(uint32_t ms);

typedef struct {{
    {lname}_spi_xfer_fn xfer;
    {lname}_cs_fn       cs;
    {lname}_delay_ms_fn delay_ms;
    void               *ctx;
}} {lname}_t;

int {lname}_init({lname}_t *dev);
int {lname}_read_reg({lname}_t *dev, uint8_t reg, uint8_t *value);
int {lname}_write_reg({lname}_t *dev, uint8_t reg, uint8_t value);

#endif /* {guard} */
"""

SPI_SOURCE = """\
/* Generated by fwcopilot from board.yaml. Confirm the command framing against:
 * {datasheet_hint}
 * In particular: the read/write bit position in the command byte, whether the
 * device needs dummy cycles, and the maximum SCK frequency.
 */
#include "{header}"

/* TODO: many SPI devices set bit 7 of the command byte for reads — verify. */
#define {tag}_READ_FLAG  0x80u

int {lname}_read_reg({lname}_t *dev, uint8_t reg, uint8_t *value)
{{
    uint8_t tx[2];
    uint8_t rx[2] = {{0u, 0u}};
    int rc;

    if (dev == NULL || dev->xfer == NULL || value == NULL) {{
        return -1;
    }}
    tx[0] = (uint8_t)(reg | {tag}_READ_FLAG);
    tx[1] = 0x00u;

    if (dev->cs != NULL) {{
        dev->cs(true, dev->ctx);
    }}
    rc = dev->xfer(tx, rx, sizeof(tx), dev->ctx);
    if (dev->cs != NULL) {{
        dev->cs(false, dev->ctx);
    }}
    if (rc == 0) {{
        *value = rx[1];
    }}
    return rc;
}}

int {lname}_write_reg({lname}_t *dev, uint8_t reg, uint8_t value)
{{
    uint8_t tx[2];
    int rc;

    if (dev == NULL || dev->xfer == NULL) {{
        return -1;
    }}
    tx[0] = (uint8_t)(reg & (uint8_t)~{tag}_READ_FLAG);
    tx[1] = value;

    if (dev->cs != NULL) {{
        dev->cs(true, dev->ctx);
    }}
    rc = dev->xfer(tx, NULL, sizeof(tx), dev->ctx);
    if (dev->cs != NULL) {{
        dev->cs(false, dev->ctx);
    }}
    return rc;
}}

int {lname}_init({lname}_t *dev)
{{
    if (dev == NULL || dev->xfer == NULL) {{
        return -1;
    }}
    /* TODO: verify the device ID register and run the datasheet reset sequence. */
    return 0;
}}
"""


def gen_drivers(board: BoardProfile) -> List[Tuple[str, str]]:
    files: List[Tuple[str, str]] = []
    for comp in board.components:
        bus_type = _bus_type(board, comp)
        base = _lower(comp.part or comp.ref)
        header_name = f"drivers/{base}.h"
        hint = comp.datasheet or f"(no datasheet linked for {comp.part or comp.ref} in board.yaml)"
        common = {
            "part": comp.part or comp.ref,
            "ref": comp.ref,
            "role_comment": f" — {comp.role}" if comp.role else "",
            "bus": comp.bus_name or "unspecified",
            "guard": _header_guard(base),
            "tag": _upper(base),
            "lname": base,
            "header": f"{base}.h",
            "datasheet_hint": hint,
        }
        if bus_type == "spi":
            cs = comp.bus.get("cs")
            files.append((header_name, SPI_HEADER.format(
                cs_comment=f", CS={cs}" if cs else "", **common)))
            files.append((f"drivers/{base}.c", SPI_SOURCE.format(**common)))
        elif bus_type == "i2c":
            files.append((header_name, I2C_HEADER.format(
                addr=_addr_literal(comp.address if comp.address is not None else 0), **common)))
            files.append((f"drivers/{base}.c", I2C_SOURCE.format(
                addr=_addr_literal(comp.address if comp.address is not None else 0), **common)))
    return files


def _bus_type(board: BoardProfile, comp: Component) -> str:
    declared = str(comp.bus.get("type") or "").lower()
    if declared:
        return declared
    for bus in board.buses:
        if str(bus.get("name")) == comp.bus_name:
            return str(bus.get("type") or "").lower()
    if comp.address is not None:
        return "i2c"
    if comp.bus.get("cs"):
        return "spi"
    return "unknown"


# --------------------------------------------------------------------------
# main.c
# --------------------------------------------------------------------------

def gen_main(board: BoardProfile) -> str:
    comps = [c for c in board.components if _bus_type(board, c) in ("i2c", "spi")]
    includes = "\n".join(f'#include "drivers/{_lower(c.part or c.ref)}.h"' for c in comps)
    decls, inits = [], []
    for comp in comps:
        base = _lower(comp.part or comp.ref)
        decls.append(f"static {base}_t {base};")
        inits.append(
            f"    /* {comp.ref}: {comp.part} on {comp.bus_name or 'unspecified bus'} */\n"
            f"    if ({base}_init(&{base}) != 0) {{\n"
            f"        board_fault(\"{base} init failed\");\n"
            f"    }}"
        )
    return f"""\
/* Generated by fwcopilot from board.yaml — application entry point.
 * Board: {board.name}
 */
#include <stdint.h>
#include "board_pins.h"
{includes}

{chr(10).join(decls)}

static void board_fault(const char *what)
{{
    (void)what;  /* TODO: log over {_first_uart(board)} and/or blink the status LED. */
    for (;;) {{
        __asm__ volatile("nop");
    }}
}}

static void board_init(void)
{{
    /* TODO: clock tree to BOARD_SYSCLK_HZ, then GPIO, then the buses below. */
{chr(10).join(f"    /* init {b.get('name')} ({b.get('type')}) */" for b in board.buses) or "    /* no buses declared in board.yaml */"}

    /* TODO: wire each device's transport callbacks to your HAL before init. */
{chr(10).join(inits) if inits else "    /* no bus-attached components declared in board.yaml */"}
}}

int main(void)
{{
    board_init();

    for (;;) {{
        /* TODO: application loop. */
    }}
}}
"""


def _first_uart(board: BoardProfile) -> str:
    for bus in board.buses:
        if str(bus.get("type", "")).lower() in ("uart", "usart"):
            return str(bus.get("name"))
    return "the debug UART"


# --------------------------------------------------------------------------
# Target-specific build files
# --------------------------------------------------------------------------

def gen_linker_script(board: BoardProfile) -> str:
    mcu = board.mcu
    flash_kb = int(mcu.get("flash_kb") or 256)
    ram_kb = int(mcu.get("ram_kb") or 64)
    flash_origin = mcu.get("flash_origin") or "0x08000000"
    ram_origin = mcu.get("ram_origin") or "0x20000000"
    return f"""\
/* Generated by fwcopilot from board.yaml ({mcu.get('part', 'unknown MCU')}).
 * Verify ORIGIN/LENGTH against the MCU datasheet memory map before flashing.
 */
ENTRY(Reset_Handler)

MEMORY
{{
    FLASH (rx)  : ORIGIN = {flash_origin}, LENGTH = {flash_kb}K
    RAM   (rwx) : ORIGIN = {ram_origin}, LENGTH = {ram_kb}K
}}

_estack = ORIGIN(RAM) + LENGTH(RAM);
_Min_Heap_Size  = 0x200;
_Min_Stack_Size = 0x400;

SECTIONS
{{
    .isr_vector : {{ KEEP(*(.isr_vector)) }} > FLASH

    .text :
    {{
        . = ALIGN(4);
        *(.text) *(.text*)
        *(.rodata) *(.rodata*)
        . = ALIGN(4);
        _etext = .;
    }} > FLASH

    .ARM.exidx : {{ *(.ARM.exidx*) }} > FLASH

    _sidata = LOADADDR(.data);
    .data :
    {{
        . = ALIGN(4);
        _sdata = .;
        *(.data) *(.data*)
        . = ALIGN(4);
        _edata = .;
    }} > RAM AT> FLASH

    .bss :
    {{
        . = ALIGN(4);
        _sbss = .;
        *(.bss) *(.bss*) *(COMMON)
        . = ALIGN(4);
        _ebss = .;
    }} > RAM

    ._user_heap_stack :
    {{
        . = ALIGN(8);
        . = . + _Min_Heap_Size;
        . = . + _Min_Stack_Size;
        . = ALIGN(8);
    }} > RAM
}}
"""


STARTUP_C = """\
/* Generated by fwcopilot — minimal Cortex-M startup.
 * The vector table below covers the core exceptions only. Append this MCU's
 * device-specific IRQ handlers from its reference manual before shipping.
 */
#include <stdint.h>

extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss, _estack;
extern int main(void);

void Reset_Handler(void);
void Default_Handler(void);

#define WEAK_ALIAS __attribute__((weak, alias("Default_Handler")))

void NMI_Handler(void)        WEAK_ALIAS;
void HardFault_Handler(void)  WEAK_ALIAS;
void MemManage_Handler(void)  WEAK_ALIAS;
void BusFault_Handler(void)   WEAK_ALIAS;
void UsageFault_Handler(void) WEAK_ALIAS;
void SVC_Handler(void)        WEAK_ALIAS;
void DebugMon_Handler(void)   WEAK_ALIAS;
void PendSV_Handler(void)     WEAK_ALIAS;
void SysTick_Handler(void)    WEAK_ALIAS;

__attribute__((section(".isr_vector"), used))
void (* const g_vectors[])(void) = {
    (void (*)(void))&_estack,
    Reset_Handler,
    NMI_Handler,
    HardFault_Handler,
    MemManage_Handler,
    BusFault_Handler,
    UsageFault_Handler,
    0, 0, 0, 0,
    SVC_Handler,
    DebugMon_Handler,
    0,
    PendSV_Handler,
    SysTick_Handler,
    /* TODO: device-specific IRQ handlers go here, in reference-manual order. */
};

void Reset_Handler(void)
{
    uint32_t *src = &_sidata;
    uint32_t *dst = &_sdata;

    while (dst < &_edata) {
        *dst++ = *src++;
    }
    for (dst = &_sbss; dst < &_ebss; dst++) {
        *dst = 0u;
    }

    /* TODO: SystemInit() / clock configuration before main(). */
    (void)main();

    for (;;) {
    }
}

void Default_Handler(void)
{
    /* Unhandled interrupt — break here in the debugger to find which. */
    for (;;) {
    }
}
"""


def gen_makefile(board: BoardProfile) -> str:
    mcu = board.mcu
    core = str(mcu.get("core") or "Cortex-M4").lower()
    if "m0" in core:
        cpu, fpu = "cortex-m0", ""
    elif "m33" in core:
        cpu, fpu = "cortex-m33", "-mfpu=fpv5-sp-d16 -mfloat-abi=hard"
    elif "m7" in core:
        cpu, fpu = "cortex-m7", "-mfpu=fpv5-d16 -mfloat-abi=hard"
    elif "m4" in core:
        cpu, fpu = "cortex-m4", "-mfpu=fpv4-sp-d16 -mfloat-abi=hard" if "f" in core else ""
    else:
        cpu, fpu = "cortex-m3", ""
    target = _lower(board.name)
    return f"""\
# Generated by fwcopilot from board.yaml ({mcu.get('part', 'unknown MCU')}).
TARGET  := {target}
BUILD   := build

CROSS   := arm-none-eabi-
CC      := $(CROSS)gcc
OBJCOPY := $(CROSS)objcopy
SIZE    := $(CROSS)size

CPUFLAGS := -mcpu={cpu} -mthumb {fpu}
CFLAGS   := $(CPUFLAGS) -std=c11 -Og -g3 -Wall -Wextra -Wshadow -Wundef \\
            -ffunction-sections -fdata-sections -I. -Idrivers
LDFLAGS  := $(CPUFLAGS) -T{target}.ld -Wl,--gc-sections -Wl,-Map=$(BUILD)/$(TARGET).map \\
            --specs=nano.specs --specs=nosys.specs

SRCS := $(wildcard *.c) $(wildcard drivers/*.c)
OBJS := $(patsubst %.c,$(BUILD)/%.o,$(SRCS))

all: $(BUILD)/$(TARGET).bin

$(BUILD)/%.o: %.c
\t@mkdir -p $(dir $@)
\t$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/$(TARGET).elf: $(OBJS)
\t$(CC) $(OBJS) $(LDFLAGS) -o $@
\t$(SIZE) $@

$(BUILD)/$(TARGET).bin: $(BUILD)/$(TARGET).elf
\t$(OBJCOPY) -O binary $< $@

clean:
\trm -rf $(BUILD)

.PHONY: all clean
"""


def gen_platformio(board: BoardProfile) -> str:
    mcu = board.mcu
    return f"""\
; Generated by fwcopilot from board.yaml.
; Set `board` to the PlatformIO board id matching {mcu.get('part', 'your MCU')}
; (see https://docs.platformio.org/en/latest/boards/).
[env:{_lower(board.name)}]
platform = ststm32
board = TODO_platformio_board_id
framework = stm32cube
build_flags =
    -Wall
    -Wextra
    -Iinclude
monitor_speed = {_uart_baud(board)}
"""


def _uart_baud(board: BoardProfile) -> int:
    for bus in board.buses:
        if str(bus.get("type", "")).lower() in ("uart", "usart") and bus.get("baud"):
            return int(bus["baud"])
    return 115200


def gen_zephyr_overlay(board: BoardProfile) -> str:
    lines = [
        "/* Generated by fwcopilot from board.yaml.",
        " * Node labels (&i2c1, &spi1) must match your Zephyr board's devicetree.",
        " */",
        "",
    ]
    for bus in board.buses:
        btype = str(bus.get("type", "")).lower()
        label = _lower(bus.get("name"))
        devices = [c for c in board.components if c.bus_name == bus.get("name")]
        if btype not in ("i2c", "spi") or not devices:
            continue
        lines.append(f"&{label} {{")
        lines.append('    status = "okay";')
        if btype == "i2c" and bus.get("speed_hz"):
            speed = int(bus["speed_hz"])
            lines.append(f"    clock-frequency = <{'I2C_BITRATE_FAST' if speed >= 400000 else 'I2C_BITRATE_STANDARD'}>;")
        for comp in devices:
            node = _lower(comp.part or comp.ref)
            if btype == "i2c" and comp.address is not None:
                addr = _addr_literal(comp.address)
                lines.append(f"    {node}: {node}@{addr[2:].lower()} {{")
                lines.append(f'        compatible = "TODO,{node}";')
                lines.append(f"        reg = <{addr}>;")
                lines.append('        status = "okay";')
                lines.append("    };")
            elif btype == "spi":
                lines.append(f"    {node}: {node}@0 {{")
                lines.append(f'        compatible = "TODO,{node}";')
                lines.append("        reg = <0>;")
                lines.append(f"        spi-max-frequency = <{int(bus.get('speed_hz') or 1000000)}>;")
                lines.append('        status = "okay";')
                lines.append("    };")
        lines.append("};")
        lines.append("")
    return "\n".join(lines) or "/* No I2C/SPI devices declared in board.yaml. */\n"


def gen_zephyr_prj(board: BoardProfile) -> str:
    lines = ["# Generated by fwcopilot from board.yaml.", "CONFIG_LOG=y", "CONFIG_GPIO=y"]
    types = {str(b.get("type", "")).lower() for b in board.buses}
    if "i2c" in types:
        lines.append("CONFIG_I2C=y")
    if "spi" in types:
        lines.append("CONFIG_SPI=y")
    if types & {"uart", "usart"}:
        lines.append("CONFIG_SERIAL=y")
        lines.append("CONFIG_UART_INTERRUPT_DRIVEN=y")
    if any(str(c.role or "").lower().find("sensor") >= 0 for c in board.components):
        lines.append("CONFIG_SENSOR=y")
    return "\n".join(lines) + "\n"


ZEPHYR_MAIN = """\
/* Generated by fwcopilot from board.yaml. */
#include <zephyr/kernel.h>
#include <zephyr/device.h>
#include <zephyr/logging/log.h>

LOG_MODULE_REGISTER(app, LOG_LEVEL_INF);

int main(void)
{
    LOG_INF("%s starting", CONFIG_BOARD);

    /* TODO: DEVICE_DT_GET() each node from the generated overlay and check
     * device_is_ready() before use. */

    while (1) {
        k_sleep(K_MSEC(1000));
    }
    return 0;
}
"""

ZEPHYR_CMAKE = """\
# Generated by fwcopilot.
cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(app)

target_sources(app PRIVATE src/main.c)
target_include_directories(app PRIVATE include)
"""


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------

def generate(board: BoardProfile, target: str) -> List[Tuple[str, str]]:
    """Return [(relative path, content)] for the chosen target."""
    if target not in TARGETS:
        raise ValueError(f"unknown target '{target}'; choose from {', '.join(TARGETS)}")
    if not board.exists:
        raise ValueError("no board.yaml found — run `fwcopilot board init` first")

    files: List[Tuple[str, str]] = [("board_pins.h", gen_board_pins(board))]
    files.extend(gen_drivers(board))

    if target == "drivers-only":
        return files

    if target == "cmsis-bare":
        files.append(("main.c", gen_main(board)))
        files.append(("startup.c", STARTUP_C))
        files.append((f"{_lower(board.name)}.ld", gen_linker_script(board)))
        files.append(("Makefile", gen_makefile(board)))
    elif target == "platformio":
        files.append(("src/main.c", gen_main(board)))
        files.append(("platformio.ini", gen_platformio(board)))
    elif target == "zephyr":
        files.append(("src/main.c", ZEPHYR_MAIN))
        files.append(("prj.conf", gen_zephyr_prj(board)))
        files.append(("CMakeLists.txt", ZEPHYR_CMAKE))
        files.append((f"boards/{_lower(board.name)}.overlay", gen_zephyr_overlay(board)))
    return files


def write_files(
    out_dir: Path, files: List[Tuple[str, str]], *, force: bool = False
) -> List[GeneratedFile]:
    written: List[GeneratedFile] = []
    for rel, content in files:
        path = out_dir / rel
        existed = path.exists()
        if existed and not force:
            written.append(GeneratedFile(rel, content, existed=True))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(GeneratedFile(rel, content, existed=existed))
    return written
